### ISSUE TITLE
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

### ISSUE THREAD

**Issue by kstanghere** [katyfelkner/winoqueer#1]
hello, when I want to pull the data, it prompts the following error: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

It could be because there are no more quotas being pulled. 

Is there another way to get the data please?

thanks a lot:)

**Comment by katyfelkner** [comment]
hey! I fixed this a few months ago but looks like I forgot to close the issue. LFS bandwidth problems should be fixed now.
